"""Fetch BIFF's own hero-image URLs, matched by the existing official film index.
Images stay on the official CDN. HTML responses are cached outside the repository.
"""
import concurrent.futures
import html
import json
import re
import tempfile
import urllib.request
from pathlib import Path

root = Path(__file__).resolve().parent.parent
metadata = json.loads((root / 'data/film-meta-2026.json').read_text())
cache = Path(tempfile.gettempdir()) / 'biff-official-still-pages'
cache.mkdir(exist_ok=True)

def fetch(item):
    idx, film = item
    url = f'https://www.biff.kr/eng/html/program/prog_view.asp?idx={idx}&c_idx={film["c_idx"]}'
    path = cache / f'{idx}.html'
    try:
        if path.exists():
            page = path.read_text()
        else:
            request = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            page = urllib.request.urlopen(request, timeout=25).read().decode('utf-8', errors='replace')
            path.write_text(page)
        match = re.search(r'class="filmtop_visual"[^>]*background-image:\s*url\([\'"]([^\'"]+)', page)
        if match:
            image = html.unescape(match[1])
            if image.startswith('https://') and '/FILM_PHOTO/' in image:
                return film['title_en'], image
        return film['title_en'], None
    except Exception as error:
        print(f'Failed {idx}: {error}', flush=True)
        return film['title_en'], None

with concurrent.futures.ThreadPoolExecutor(max_workers=6) as pool:
    results = dict(pool.map(fetch, metadata.items()))
images = {title: image for title, image in sorted(results.items()) if image}
output = root / 'src/app/official-stills.ts'
output.write_text('// Official BIFF hero-image URLs. Generated by tools/fetch_official_stills.py.\n'
                  + 'export const officialStills: Record<string, string> = '
                  + json.dumps(images, ensure_ascii=False, indent=2) + ';\n')
print(f'Official stills: {len(images)}/{len(metadata)}. Missing: {[t for t,v in results.items() if not v]}', flush=True)
